services:
  pulumi:
    build: ./infra/pulumi
    working_dir: /infra
    volumes:
      - ./infra/pulumi:/infra
      - pulumi_plugins:/root/.pulumi/plugins
    env_file:
      - path: .env
        required: false
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      PULUMI_ACCESS_TOKEN: ${PULUMI_ACCESS_TOKEN:-}
      PULUMI_STACK: ${PULUMI_STACK:-prod}

  awscli:
    image: amazon/aws-cli:2.17.0
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - path: .env
        required: false
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-}

volumes:
  pulumi_plugins:
